// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFidRegistrySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFidRegistrySystem {
  function tn_ns_1__registerFid(uint32 fid, address owner) external;

  function tn_ns_1__deleteFid(uint32 fid) external;
}
